# metadata specialised for each experiment
core:
  project_name: sentence_aligner
  storage_dir: ${oc.env:PROJECT_ROOT}/storage
  data_dir: ${oc.env:PROJECT_ROOT}/data/opus/books
  version: 0.0.1
  tags: null

defaults:
  - hydra: default
  - nn: default
  - train: default
  - _self_ # as last argument to allow the override of parameters via this main config
#    Decomment this parameter to get parallel job running
#  - hydra/launcher: joblib
